spring:
  application:
    name: dear-comrade-batch-integration-zero-to-hero
  datasource:
    url: jdbc:postgresql://localhost:5432/dha
    username: comrade
    password: dear
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#    properties:
#      hibernate:
#        jdbc:
#          batch_size: 10
#        order_inserts: true
#        order_updates: true
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false

