spring:
  application:
    name: dear-comrade-batch-integration-zero-to-hero
  batch:
    job:
      enabled: false
  datasourceOld:
    url: jdbc:postgresql://172.21.0.2:5432/dha
    username: comrade
    password: dear
  datasourceLatest:
    url: jdbc:postgresql://172.21.0.2:5432/dha-latest
    username: comrade
    password: dear
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
